package com.anthunt.poi.demo;

import org.apache.poi.ss.usermodel.CellType;

import com.anthunt.poi.template.helper.PoiLogger;
import com.anthunt.poi.template.model.enums.DBDataType;
import com.anthunt.poi.template.model.enums.NumericFormatType;
import com.anthunt.poi.template.model.excel.ExcelSheets;

/**
 * <b>엑셀 템플릿 양식 생성 샘플</b>
 * <p>
 * 	엑셀 템플릿 양식을 Java 코드로 직접 생성
 * </p>
 * 
 * @author anthunt
 *
 */
public class DemoExcelTemplate {

	private static PoiLogger logger = PoiLogger.getLogger(DemoExcelTemplate.class);
	
	/**
	 * 생성된 엑셀 템플릿 양식 정보 반환 메소드
	 * 
	 * @return ExcelSheets
	 */
	public static ExcelSheets getExcelSheets() {
		
		logger.info("start make ExcelSheets.");
		ExcelSheets excelSheets = new ExcelSheets();
		
		excelSheets.builder().setSheetName("Skip Sheet").setSkipSheet(true).build();
		logger.info("skip sheet configured.");
		
		excelSheets.builder()
					.setSheetName("TestSheet1")
					.setSheetTitle("01. Sheet Title")
					.setUseSampleData(true)
					.setExplainRowSize(1)
					.setHeaderRowSize(2)
					.addExcelColumn()
			       		.addHeaderColumn()
			       			.setValue("이름")
			                .setComment("만약 \"동명이인\" 이 있을경우 이름뒤에 숫자를 붙여 구분\nEx> 홍길동이 한 회사에 두명일 경우: 홍길동1, 홍길동2 로 기재\n\n한명이 회계연도 중간에 직/간접/일반 업무전환시 이름뒤에 XXX(직), XXX(간), XXX(일) 로 구분\nEx>직접 6개월, 간접 6개월 근무한 경우: 홍길동(직), 홍길동(간)  으로 기재")
			                .setRowMergeSize(2)
			                .and()
			            .addExplainColumn()
			            	.setValue("-셀서식(일반)\n-사업참여자명(필수항목)")
			            	.and()
			    		.setRequired(true)
			    		.setCellType(CellType.STRING)
			    		.setSampleValue("홍길동")	
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN1")
			    			.setDataType(DBDataType.STRING)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("직급")
			    			.setRowMergeSize(2)
			    			.and()
			    		.setRequired(true)
			    		.setCellType(CellType.STRING)
			    		.setSampleValue("대리")
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN2")
			    			.setDataType(DBDataType.STRING)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("구분1")
			    			.setComment("직접/간접/일반으로 기재")
			    			.setRowMergeSize(2)
			    			.and()
			    		.setRequired(true)
			    		.setCellType(CellType.STRING)
			    		.setDataExplicits(new String[]{"직접", "간접", "일반"})
			    		.setSampleValue("직접")
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN3")
			    			.setDataType(DBDataType.STRING)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("부서명")
			    			.setRowMergeSize(2)
			    			.and()
			    		.setRequired(true)
			    		.setCellType(CellType.STRING)
			    		.setSampleValue("제조팀")
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN4")
			    			.setDataType(DBDataType.STRING)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("구분2")
			    			.setComment("정규직/계약직으로 기재")
			    			.setRowMergeSize(2)
			    			.and()
			    		.setRequired(true)
			    		.setCellType(CellType.STRING)
			    		.setDataExplicits(new String[]{"정규직", "계약직"})
			    		.setSampleValue("정규직")
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN5")
			    			.setDataType(DBDataType.STRING)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("급여대장")
			    			.setCellMergeSize(15)
			    			.setSkipRequired(true)
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("구분3")
			    			.and()
			    		.setRequired(true)
			    		.setCellType(CellType.STRING)
			    		.setDataExplicits(new String[]{"급여", "상여"})
			    		.setSampleValue("급여")
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN6")
			    			.setDataType(DBDataType.STRING)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("구분4")
			    			.and()
			    		.setRequired(true)
			    		.setCellType(CellType.STRING)
			    		.setDataExplicits(new String[]{"기본급", "제수당(잔/특근)", "제수당(기타수당)", "정기상여", "비정기상여"})
			    		.setSampleValue("기본급")
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN7")
			    			.setDataType(DBDataType.STRING)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("1월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "1월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("2월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "2월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("3월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "3월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("4월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "4월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("5월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "5월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("6월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "6월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("7월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "7월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("8월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "8월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("9월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "9월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("10월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "10월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("11월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "11월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("12월")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.NUMERIC)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setSampleValue(1800000)
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN9")
			    			.setDataType(DBDataType.NUMERIC)
			    			.setPivotColumn("COLUMN8", "12월", true)
			    			.and()
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("")
			    			.and()
			    		.addHeaderColumn()
			    			.setValue("소계")
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.FORMULA)
			    		.setNumericFormatType(NumericFormatType.INTEGER)
			    		.setColumnFormula("SUM({COL8}{ROW}:{COL19}{ROW})")
			    		.and()
			    	.addExcelColumn()
			    		.addHeaderColumn()
			    			.setValue("비고")
			    			.setRowMergeSize(2)
			    			.and()
			    		.setRequired(false)
			    		.setCellType(CellType.STRING)
			    		.setSampleValue("비고")
			    		.addDBColumn()
			    			.setTableName("TABLE_NAME1")
			    			.setColumnName("COLUMN10")
			    			.setDataType(DBDataType.STRING)
			    			.and()
			    		.and()
			    	.build();
		
		logger.info("finished make ExcelSheets.");
		
		return excelSheets;
	}
	
}
